import type { Metadata } from "next";
import "@carbon/styles/css/styles.css";

import I18nProvider from "@/providers/I18nProvider"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en"> 
      <body>
        <I18nProvider>
          <main>{children}</main>
        </I18nProvider>
      </body>
    </html>
  );
}